server:
  port: 9191

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/libre_ai
    username: libre
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 0
      minimum-idle: 1
      connection-test-query: SELECT 1

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    drop-first: false

dashboard:
  openai:
    api-key: ${OPENAI_API_KEY}
    base-url: ${OPENAI_BASE_URL}
    model-name: ${OPENAI_MODEL_NAME:qwen3}
    temperature: ${OPENAI_TEMPERATURE:1}
    max-tokens: ${OPENAI_MAX_TOKENS:12800}

  generation:
    timeout: ${DASHBOARD_TIMEOUT:120000}
    max-retries: ${DASHBOARD_MAX_RETRIES:3}
    enable-cache: ${DASHBOARD_ENABLE_CACHE:false}

rag:
  embedding:
    batch-size: ${RAG_EMBEDDING_BATCH_SIZE:50}

logging:
  level:
    org.libre.ai.modules.dashboard: debug
    dev.langchain4j: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

aws:
  s3:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    # region: ${AWS_REGION:us-east-1}
    endpoint: ${AWS_S3_ENDPOINT}
    path-style-access: ${AWS_S3_PATH_STYLE_ACCESS:true}


