server:
  port: 9191

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/libre_ai
    username: libre
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 0
      minimum-idle: 1
      connection-test-query: SELECT 1

  # Liquibase数据库版本管理配置
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    # 在开发环境下可以设置为true，生产环境建议设置为false
    drop-first: false
  profiles:
    active: dev

# Dashboard Generator模块配置
# 遵循配置外部化原则：所有配置通过环境变量或配置文件管理
dashboard:
  # OpenAI配置
  openai:
    # API密钥，建议通过环境变量OPENAI_API_KEY设置
    api-key: ${OPENAI_API_KEY}
    # API基础URL，支持代理或自定义端点
    base-url: ${OPENAI_BASE_URL}
    # 使用的模型名称
    model-name: ${OPENAI_MODEL_NAME:qwen3}
    # 温度参数，控制输出随机性（0-1）
    temperature: ${OPENAI_TEMPERATURE:1}
    # 最大输出token数
    max-tokens: ${OPENAI_MAX_TOKENS:12800}

  # 代码生成配置
  generation:
    # AI调用超时时间（秒）
    timeout: ${DASHBOARD_TIMEOUT:120000}
    # 最大重试次数
    max-retries: ${DASHBOARD_MAX_RETRIES:3}
    # 是否启用结果缓存
    enable-cache: ${DASHBOARD_ENABLE_CACHE:false}


# 日志配置（可选）
logging:
  level:
    org.libre.ai.modules.dashboard: debug
    dev.langchain4j: DEBUG

# AWS S3配置
aws:
  s3:
    # AWS访问密钥ID
    access-key-id: ${AWS_ACCESS_KEY_ID}
    # AWS访问密钥
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    # S3存储桶名称
    bucket-name: ${AWS_S3_BUCKET_NAME:libre-ai}
    # AWS区域
  #  region: ${AWS_REGION:us-east-1}
    # 自定义端点（可选，用于兼容S3的对象存储服务如MinIO）
    endpoint: ${AWS_S3_ENDPOINT:https://minio.zclibre.org}
    # 是否启用路径样式访问（MinIO等需要设置为true）
    path-style-access: ${AWS_S3_PATH_STYLE_ACCESS:true}